### ISSUE TITLE
8088 decompressors won't run on 8088

### ISSUE THREAD

**Issue by MobyGamer** [emmanuel-marty/lzsa#3]
Hi, there's a few instances of this:

shl al,2

...which actually require an 80186 or higher to work.  These should be replaced with:

shl al,1
shl al,1

**Comment by emmanuel-marty** [comment]
Ah, whoops, thanks! I'll update the code. Note that it could be much more
optimized for speed, notably neither LZSA1 or LZSA2 depackers are currently
detecting run-lengths and using rep stosb/w as in your LZ4 decompressor,
and it definitely would help. I'm sure you can spot tons of other ways to
speed it up as well.

**Comment by emmanuel-marty** [comment]
Fixed, thanks. I'll be honored if you want to take a further look at improving the 8088 depackers as well.

**Comment by MobyGamer** [comment]
> I'll be honored if you want to take a further look at improving the 8088 depackers as well.

Was already planning on it ;-)
