### ISSUE TITLE
[Question] Cortex M4 assembly decompressor

### ISSUE THREAD

**Issue by shazz** [emmanuel-marty/lzsa#4]
Salut Emmanuel,

Before I spend time in learning the ARM/Cortex M4 assembly, did you already code an assembly or C-optimized version of the decompressor ?

My hardware targets are STM32F4 and ATSMAD51.

Merci!

**Comment by emmanuel-marty** [comment]
I haven't coded an ARM version of the decompressors, I'll be happy to get one :-) The C depacker for LZSA1/2 (expand_block_v1.c and v2.c respectively) is probably a good starting point, happy to answer any questions as well
