### ISSUE TITLE
Bug in decompress_small_v1.S for 8088?

### ISSUE THREAD

**Issue by odzhan** [emmanuel-marty/lzsa#41]
The following is compressed using lzsa on Linux : lzsa -f1 -r test.txt test.bin

```
00000000: 5468 6973 2069 7320 6120 7465 7374 2066  This is a test f
00000010: 6f72 204c 5a53 4131 2064 6563 6f6d 7072  or LZSA1 decompr
00000020: 6573 736f 7220 696e 2038 3038 3820 6173  essor in 8088 as
00000030: 7365 6d62 6c79 2e0a                      sembly..
```

Which results in the following.
```

00000000: 5054 6869 7320 fd7f 2961 2074 6573 7420  PThis ..)a test 
00000010: 666f 7220 4c5a 5341 3120 6465 636f 6d70  for LZSA1 decomp
00000020: 7265 7373 6f72 2069 6e20 3830 3838 2061  ressor in 8088 a
00000030: 7373 656d 626c 792e 0a00 ee00 00         ssembly......
```

However, when trying to decompress this using the decompress_small_v1.S, it doesn't appear to decompress properly.

```
00000000: 5468 6973 2000 0000 6120 7465 7374 2066  This ...a test f
00000010: 6f72 204c 5a53 4131 2064 6563 6f6d 7072  or LZSA1 decompr
00000020: 6573 736f 7220 696e 2038 3038 3820 6173  essor in 8088 as
00000030: 7365 6d62 6c79 2e0a                      sembly..
```

Any idea what's wrong and why "is" doesn't decompress? When I decompress with the lzsa app, it works fine.

**Comment by specke** [comment]
Could you please provide a minimum code+data example?

**Comment by odzhan** [comment]
[lzsa_test.zip](https://github.com/emmanuel-marty/lzsa/files/4050746/lzsa_test.zip)

Build: 
yasm -fwin32 lzsa.asm -olzsa.obj
cl lzsa_test.c lzsa.obj

Use: 
lzsa_test test.bin test.txt

**Comment by MobyGamer** [comment]
Does it decompress correctly using the other (speed-optimized) variant of the code?

**Comment by odzhan** [comment]
Similar problem with the fast code. I converted to 32-bit for testing. See attached. I should probably add in a simple checksum to verify decompression.

[lzsa_test.zip](https://github.com/emmanuel-marty/lzsa/files/4050935/lzsa_test.zip)

**Comment by odzhan** [comment]
Not for me although perhaps I'm doing it wrong. Replied to you on github.

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by odzhan** [comment]
Not sure if it's related. I noticed memcpy is storing eight bytes, ignoring the value of nLiterals.

 ```
     const unsigned char token = *pInBlock++;
      // isolate literals length in token
      unsigned int nLiterals = (unsigned int)((token & 0x70) >> 4);

      if(nLiterals != LITERALS_RUN_LEN_V1) {
        // store eight bytes
        memcpy(pCurOutData, pInBlock, 8);
      } else {
        if(nLiterals == LITERALS_RUN_LEN_V1) {
          nByte = *pInBlock++;
          nLiterals += nByte;
          
          if (nByte == 250) {
            nLiterals = 256 + ((unsigned int)*pInBlock++);
          } else if (nByte == 249) {
            nLiterals = ((unsigned int)*pInBlock++);
            nLiterals |= (((unsigned int)*pInBlock++) << 8);
          }
        }
        memcpy(pCurOutData, pInBlock, nLiterals);
      }
```

**Comment by MobyGamer** [comment]
I tested the 8088 code I wrote (the speed versions) and they test perfectly with your source data.  My test procedure:

1. Took your source hexdump and made it a file
2. Compressed it with the win32 compressor
3. Decompressed it using https://github.com/emmanuel-marty/lzsa/blob/master/asm/8088/LZSA1FTA.ASM in an emulator
4. Compared to original (identically)

If there are errors, they are either in the NASM conversions of the code I contributed, or in your 32-bit conversion of that code.

EDIT:  Checking your 32-bit code conversion, you're calling xlat when the original source is cs:xlat.  xlat pulls from DS unless an override is given.  I don't see you making DS=CS, so if the translation table is in CS then that's not going to work.

How I would convert this code to 32-bit is I'd start by _only_ changing di/si to edi/esi to ensure the code works; then I'd move on to other optimizations, testing at each iteration.

**Comment by odzhan** [comment]
I've commented out the instructions so you can see what's been changed.

[lzsa2.txt](https://github.com/emmanuel-marty/lzsa/files/4051054/lzsa2.txt)

Did you try using the compressed data in first post with your code? Does it match with compressed data from your win32 compressor?

**Comment by MobyGamer** [comment]
The output of the win32 lzsa compressor matched the file you provided.  I did this to ensure the compressor wasn't generating incorrect data.

The original code makes assumptions that it is running in real mode, with DS:SI set to the source and ES:DI set to the destination, and CS:BX set to the shift table.  Since you changed cs:xlat to xlatb, the shift isn't working because xlatb pulls from ds:bx, so change that to shr al,4 (you don't need the table either, 32-bit is faster than the table).  See if that fixes your issue.

In the original code, when match copies occur, ds is changed to point to the output buffer because the match is from inside the output buffer, then after the rep movsb is finished it is changed back to the compressed source.  I don't think your code is doing this; I don't see any DS manipulations.

Try fixing these both and seeing if that helps.

**Comment by peterferrie** [comment]
Before the "add esi,edx", do a "movsx edx,dx".  It's a signed value to sign-extend the 16-bit value to a signed 32-bit value.

**Comment by odzhan** [comment]
Thank you Peter. Boss!😁
