### ISSUE TITLE
MC68000 depacker source

### ISSUE THREAD

**Issue by ggnkua** [emmanuel-marty/lzsa#43]
Hi there,

Just letting you know that there is a 68k depack source for both LZSA formats here: https://github.com/tattlemuss/lz4-m68k/blob/master/src/lzsa.s

At the author mentions, it's not super optimised but it's correct, so I figure it's better than starting from scratch :)

**Comment by emmanuel-marty** [comment]
Thank you for the info! I added the link to the project's README.md.
