### ISSUE TITLE
8086 depacker for non-raw LZSA2 file

### ISSUE THREAD

**Issue by ecm-pushbx** [emmanuel-marty/lzsa#61]
Hello,

I used your NASM source for the space-efficient 8088 LZSA2 raw decompressor to build [my 8086 depacker](https://hg.ulukai.org/ecm/inicomp/file/c1a1f9bd4382/lzsa2.asm) for the lDOS/lDebug/RxDOS kernel file.

I use `-f2` for the `lzsa` tool to create an LZSA2 compressed stream. My files are usually larger than 64 KiB so using raw blocks was not an option.

I adapted your source so it counts down the remaining lengths of the source and destination. This provides a simple type of error check. I also added checks for the end of the block data [similar to your C source](https://github.com/emmanuel-marty/lzsa/blob/5cfec00d87b8bdcd5106bb7de43765ddf4a73939/src/expand_block_v2.c#L149). I further made it so a back reference can cross a segment boundary by doing segment arithmetic. I changed the code not to use `bp` so I can use it as a stack frame base pointer throughout. Finally, I added support for overlapping source and destination buffers which checks the far pointers after every match to insure the source data is not corrupted.

**Comment by ecm-pushbx** [comment]
The stream format documentation [on the length](https://github.com/emmanuel-marty/lzsa/blob/5cfec00d87b8bdcd5106bb7de43765ddf4a73939/StreamFormat.md#frame-format) could be clearer by the way. I had to inspect the actual output and code to determine that 1. it is the length of the **compressed** data of this block and 2. that there is no End Of Data marker in the block's data as for raw blocks, but rather the depacker has to detect when it read enough of the block's data.

**Comment by ecm-pushbx** [comment]
To be fair I just reviewed the LZSA2 block format [description of the EOD marker](https://github.com/emmanuel-marty/lzsa/blob/5cfec00d87b8bdcd5106bb7de43765ddf4a73939/BlockFormat_LZSA2.md#end-of-data-detection-for-raw-blocks) and it does list that this is only used for raw blocks.

**Comment by emmanuel-marty** [comment]
Thanks, linked in the README file
